insert into skill (s_code, s_desc) values
('AA', 'Dive deeply'),
('AB', 'Glide along the surface'),
('AC', 'Surf on waves'),
('AD', 'Jet propulsion'),
('AE', 'Crawl along the seabed'),
('AF', 'Leap out of water'),
('AG', 'Skim across the water'),
('AH', 'Twist in whirlpools'),
('AI', 'Hover just above water'),
('AJ', 'Ride currents'),
('AK', 'Sense water salinity'),
('AL', 'Detect vibrations in water'),
('AM', 'Track thermal gradients'),
('AN', 'See clearly underwater'),
('AO', 'Use sonar-like echolocation'),
('AP', 'Feel changes in pressure'),
('AQ', 'Sense water purity'),
('AR', 'Detect bioelectric fields'),
('AS', 'Spot camouflaged underwater creatures'),
('AT', 'Hear low frequency sounds underwater'),
('AU', 'Control water currents'),
('AV', 'Form water bubbles for traps'),
('AW', 'Create protective water shields'),
('AX', 'Generate tidal waves'),
('AY', 'Summon rain'),
('AZ', 'Split water apart'),
('BA', 'Turn water into ice'),
('BB', 'Boil water on contact'),
('BC', 'Shape water into weapons'),
('BD', 'Absorb water to grow larger'),
('BE', 'Mimic water ripples'),
('BF', 'Blend into water reflections'),
('BG', 'Generate fog'),
('BH', 'Shimmer like a mirage'),
('BI', 'Adapt to freshwater or saltwater'),
('BJ', 'Transform into a liquid state'),
('BK', 'Create bio-luminescent light underwater'),
('BL', 'Change skin texture to mimic coral'),
('BM', 'Develop water-repellent surfaces'),
('BN', 'Generate a transparent body'),
('BO', 'Filter feed plankton'),
('BP', 'Spit water to capture prey'),
('BQ', 'Trap prey in whirlpools'),
('BR', 'Ambush prey using stillness'),
('BS', 'Release decoys made of water'),
('BT', 'Use tentacles made of liquid'),
('BU', 'Expel toxic water jets'),
('BV', 'Digest prey underwater'),
('BW', 'Lure prey with glowing patterns'),
('BX', 'Hunt by disorienting prey with waves'),
('BY', 'Exude a slick, slippery coating'),
('CA', 'Release blinding mists'),
('CB', 'Create decoy water shadows'),
('CC', 'Harden water into barriers'),
('CD', 'Self-heal in water'),
('CE', 'Dissolve temporarily into water'),
('CF', 'Emit ultrasonic deterrents'),
('CG', 'Camouflage as harmless driftwood'),
('CH', 'Deflect attacks with water shields'),
('CI', 'Turn into a water cyclone'),
('CJ', 'Extract oxygen from water'),
('CK', 'Store water inside the body'),
('CL', 'Survive in extreme depths'),
('CM', 'Hibernate in frozen water'),
('CN', 'Consume water for energy'),
('CO', 'Adapt gills to air temporarily'),
('CP', 'Regenerate using surrounding water'),
('CQ', 'Filter out toxins from water'),
('CR', 'Store water for long migrations'),
('CS', 'Conserve water in arid zones'),
('CT', 'Lay eggs in floating foam'),
('CU', 'Create currents to carry young'),
('CV', 'Incubate offspring in water sacs'),
('CW', 'Disguise eggs as pebbles'),
('CX', 'Release pheromones into water'),
('CY', 'Protect eggs in underwater caves'),
('CZ', 'Synchronize spawning with tides'),
('DA', 'Use water vibrations to signal mates'),
('DB', 'Carry offspring in pockets of water'),
('DC', 'Camouflage young with algae'),
('DD', 'Turn water into mist'),
('DE', 'Conjure waterfalls'),
('DF', 'Summon creatures made of water'),
('DG', 'Purify polluted water'),
('DH', 'Create endless rainbows'),
('DI', 'Teleport via water bodies'),
('DJ', 'Convert water to healing springs'),
('DK', 'Control water elementals'),
('DL', 'Bring statues to life using water'),
('DM', 'Merge with water spirits'),
('DN', 'Sing with water vibrations'),
('DO', 'Shape-shift into water forms'),
('DP', 'Write messages in water patterns'),
('DQ', 'Absorb memories from water droplets'),
('DR', 'Create music with flowing water'),
('DS', 'Grow stronger in storms'),
('DT', 'Turn water into adhesive slime'),
('DU', 'Split into smaller water clones'),
('DV', 'Harness lightning through water'),
('DW', 'Transform water into steam to escape');

update skill set origin_t_id = ascii(substring(s_code, 2, 1)) - 63 where length(s_code) = 2;
