source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'
gem 'yaml'

group 'development' do
  gem 'pry'
  gem 'faker'
end

group 'test' do
  gem 'rspec'
end

group 'development', 'test' do
  gem 'pry'
end